### ISSUE TITLE
As a player, I would like to start a game with a hand of cards

### ISSUE THREAD

**Issue by cclp94** [DrunkDutch/comp-354#11]
- [x] Draw cards from the deck (#12)
- [x] Put cards on rewards (#13)
- [x] Give cards to players' hands (#14)
- [x] Validate hand and implement Mulligans (#15)
