### ISSUE TITLE
As a player, I would like to load a deck

### ISSUE THREAD

**Issue by cclp94** [DrunkDutch/comp-354#2]
Include issues here
- [x] Parse Cards file (#3)
- [x] Parse Ability file (#4)
- [x] Create a deck (#7)
- [x] Implement Basic type Pokemon (#9)
- [x] Implement Energy cards (#10)
- [x] Implement Card Containers and deck (#37)
